version: '3'

services:
  redis:
    image: redis
    ports:
     - '6379:6379'
  web:
    build: .
    env_file: docker/production/.env
    command: python3 contabilidad/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    env_file: docker/production/.env
    command: celery worker --app=contabilidad.contabilidad.celery.app -B
    links:
      - redis