# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rfc',
            field=models.CharField(default=None, max_length=13, null=True),
        ),
    ]
