# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20180418_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='branch',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='registration_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='registration_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='rfc',
            field=models.CharField(default=None, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='sector',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
