# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20180418_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
