# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20180420_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('code', 'description')},
        ),
    ]
