# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_auto_20180420_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
