# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suburb', to='membership.Municipality'),
        ),
    ]
