# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 19:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_auto_20180424_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='zip_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), default=None, null=True, size=None),
        ),
    ]
