# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_auto_20180424_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='phone',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='phone',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
