# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0024_auto_20180425_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
