# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_auto_20180425_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tariff_fraction',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='tariff_fraction',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='tariff_fraction',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
