# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 22:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0028_auto_20180425_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='pdf_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
