# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0029_membershiprequest_pdf_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='attachment',
            field=models.ManyToManyField(to='membership.AttachedFile'),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='type',
            field=models.CharField(choices=[('CONSTITUTIVE_ACT', 'Acta Constitutiva'), ('LEGAL_POWER', 'Poder Legal'), ('EMPLOYERS_FEED', 'Cuota Patronal'), ('LEGAL_REPRESENTATIVE_OFFICIAL_ID', 'Identificación Oficial del Representante Legal'), ('LAST_TAX_RETURN', 'Ultima declaración'), ('RFC', 'R.F.C.'), ('OFFICIAL_ID', 'Identificación Oficial'), ('REGISTRATION_REGISTER', 'Inscripción del Padrón'), ('LAST_EMPLOYERS_FEED', 'Ultima cuota Patronal'), ('MEMBERSHIP_REQUEST_FORM', 'Solicitud de Afiliación impresa firmada por representante legal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='sat_taxpayer_type',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Moral')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='sat_taxpayer_type',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Moral')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='sat_taxpayer_type',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Moral')], default=None, null=True),
        ),
    ]
