# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0030_auto_20180502_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='hidden',
            field=models.NullBooleanField(default=False),
        ),
    ]
