# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0031_membershiprequest_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hidden',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='hidden',
            field=models.NullBooleanField(default=False),
        ),
    ]
