# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0032_auto_20180502_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('code', 'description'),
            },
        ),
        migrations.CreateModel(
            name='RegionDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='membership.Region')),
            ],
            options={
                'ordering': ('code', 'description'),
            },
        ),
    ]
