# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0033_region_regiondelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='attachment',
            field=models.ManyToManyField(to='membership.AttachedFile'),
        ),
    ]
