# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0034_updaterequest_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('paid', models.NullBooleanField(default=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.FileField(null=True, upload_to='payments')),
                ('payment_date', models.DateField()),
                ('invoice_pdf', models.FileField(null=True, upload_to='invoices')),
                ('invoice_xml', models.FileField(null=True, upload_to='invoices')),
                ('bank_name', models.CharField(max_length=250)),
                ('bank_account', models.CharField(max_length=250)),
                ('bank_account_clabe', models.CharField(max_length=250)),
                ('bank_reference', models.CharField(max_length=250)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.Member')),
            ],
            options={
                'ordering': ('member', 'creation_datetime'),
            },
        ),
    ]
