# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0035_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_submitted',
            field=models.NullBooleanField(default=None),
        ),
    ]
