# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expiration_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='has_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='membership_has_expired',
            field=models.BooleanField(default=False),
        ),
    ]
