# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 15:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180328_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
