# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_certification_productservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certification',
            field=models.ManyToManyField(related_name='companies', to='customer.Certification'),
        ),
        migrations.AddField(
            model_name='company',
            name='product_services',
            field=models.ManyToManyField(related_name='companies', to='customer.ProductService'),
        ),
    ]
