# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180502_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='product_services',
            new_name='product_service',
        ),
    ]
