# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180502_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delegation',
            field=models.CharField(blank=True, max_length=250, verbose_name='Delegation Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='sat_tax_payer_type',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Moral')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=250, verbose_name='State Name'),
        ),
    ]
