# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180514_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='code',
        ),
        migrations.AddField(
            model_name='certification',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='customer.Company'),
        ),
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(default=1, upload_to='certifications/attachment'),
        ),
        migrations.AddField(
            model_name='certification',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
