# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20180518_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='public',
        ),
        migrations.AddField(
            model_name='company',
            name='certification_is_public',
            field=models.BooleanField(default=True),
        ),
    ]
